FROM node:16

WORKDIR /app
 
COPY package*.json /app/

RUN npm install

RUN npm install -g typescript

RUN npm install -g next

COPY ./ /app/

RUN npm run build

FROM nginx:stable-alpine as production-stage
COPY  ./nginx.conf /etc/nginx/conf.d/default.conf

COPY --from=build-stage /app/dist /usr/share/nginx/html

CMD ["npm", "start", "daemon off;", "nginx", "-g"] 

EXPOSE 3000
