From node:16

MAINTAINER tony <tpgjs0527@naver.com>

RUN sed -i "s/^exit 101$/exit 0/" /usr/sbin/policy-rc.d

RUN apt-get update && apt-get install git -y
RUN echo "git install"

RUN npm install -g pm2
ENV NODE_ENV production

RUN mkdir -p /app
WORKDIR /app

RUN git clone https://lab.ssafy.com/s06-blockchain-nft-sub2/S06P22E206.git
WORKDIR /app/S06P22E206

COPY ./processes.json /app/S06P22E206

RUN npm install

EXPOSE 3000

CMD ["pm2-docker", "processes.json"]
